using UnityEngine;
using UnityEngine.AI;

namespace Journey
{
    public class AgentMovement : MonoBehaviour
    {
        private Vector3 target;
        private NavMeshAgent agent;

        private void Awake()
        {
            agent = GetComponent<NavMeshAgent>();
            agent.updateRotation = false;
            agent.updateUpAxis = false;
        }

        private void Update()
        {
            SetTargetPosition();
            SetAgentPosition();
        }

        private void SetTargetPosition()
        {
            if (Input.GetMouseButtonDown(0))
            {
                target = Camera.main.ScreenToWorldPoint(Input.mousePosition);
            }
        }

        private void SetAgentPosition()
        {
            agent.SetDestination(new Vector3(target.x, target.y, transform.position.z));
        }


    }
}

